version: '2'
services:
  db:
    image: mysql:5.7
    container_name: db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
    volumes:
      - ./volumes/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/mysql:/var/lib/mysql
      - ./volumes/mysql/mysqldump:/mysqldump

  drupal:
    image: drupal:8
    container_name: drupal
    volumes:
      - ./volumes/drupal/src:/var/www/html
      - ./volumes/drupal/php.ini:/usr/local/etc/php/php.ini
      - ./volumes/drupal/private:/files/private
      - ./volumes/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

    ports:
      - 8600:80

  drush:
    image: jungleran/drush:drupal8
    container_name: drush
    volumes_from:
      - drupal
    working_dir: /var/www/html
    entrypoint:
      - bash
    tty: true
    volumes:
      - ~/.cache/composer:/composer/cache
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    hostname: pma
    environment:
      - PMA_HOST=db
    ports:
      - 8601:80
